#pragma once

enum CACHED_IN
{
	CI_QUERY1 = 0,
	CI_QUERY2 = 1,
	CI_TEST = 2,
	CI_REQUEST_SAVE_BUFF_LIST = 3,
	CI_REQUEST_LOAD_BUFF_LIST = 4,
	CI_REQUEST_LOAD_VOTE_POINTS = 5,
	CI_REQUEST_SAVE_VOTE_POINTS = 6,
	CI_REQUEST_LOAD_DONATE_POINTS = 7,
	CI_REQUEST_SAVE_DONATE_POINTS = 8,
	CI_REQUEST_LOAD_PVP_DATA = 9,
	CI_REQUEST_SAVE_PVP_POINTS = 10,
	CI_REQUEST_SAVE_PVP_STAT = 11,
	CI_REQUEST_LOAD_CERTIFICATION_SKILLS = 12,
	CI_REQUEST_LOAD_CHAMPIONSHIP_TEAMS = 13,
	CI_REQUEST_LOAD_CHAMPIONSHIP_MATCHES = 14,
	CI_REQUEST_SAVE_CHAMPIONSHIP_TEAM = 15,
	CI_REQUEST_SAVE_CHAMPIONSHIP_MATCH = 16,
	CI_REQUEST_SAVE_TRANSFERRED_PVP_POINTS = 17,
	CI_REQUEST_LOAD_PVP_SEASON = 18,
	CI_REQUEST_PROCESS_PVP_SEASON = 19,
	CI_REQUEST_SET_PVP_REWARD_FLAG = 20,
	CI_REQUEST_LOAD_PVP_TOP_PLAYERS = 21,
	CI_REQUEST_SAVE_GM_LOGIN = 22,
	CI_REQUEST_SAVE_GM_LOGOUT = 23,
	CI_REQUEST_SAVE_HWID = 24,
	CI_REQUEST_SET_ITEM_LOCK_PASSWORD = 25,
	CI_REQUEST_SET_ITEM_LOCK_STATE = 26,
	CI_REQUEST_LOAD_ITEM_LOCKS = 27,
	CI_REQUEST_LOAD_BANNED_HWID = 28,
	CI_REQUEST_UNBAN_HWID = 29,
	CI_REQUEST_BAN_HWID = 30,
	CI_REQUEST_SAVE_REAL_IP = 31,
	CI_REQUEST_LOAD_AIO = 32,
	CI_REQUEST_SAVE_AIO = 33
};

enum CACHED_OUT
{
	CO_TEST = 1,
	CO_REPLY_LOAD_BUFF_LIST = 2,
	CO_REPLY_LOAD_VOTE_POINTS = 3,
	CO_REPLY_LOAD_DONATE_POINTS = 4,
	CO_REPLY_LOAD_PVP_DATA = 5,
	CO_REPLY_LOAD_CERTIFICATION_SKILLS = 6,
	CO_REPLY_LOAD_CHAMPIONSHIP_TEAM = 7,
	CO_REPLY_LOAD_CHAMPIONSHIP_MATCH = 8,
	CO_REPLY_LOAD_PVP_SEASON = 9,
	CO_REPLY_LOAD_PVP_TOP_PLAYERS = 10,
	CO_REPLY_LOAD_ITEM_LOCK = 11,
	CO_REPLY_LOAD_BANNED_HWID = 12,
	CO_REPLY_LOAD_AIO = 13
};